export interface RawLokSabhaMember {
  name: string;
  party: string;
  constituency: string;
  state: string;
  status: string;
  terms: string;
}

export const rawLokSabhaMembers: RawLokSabhaMember[] = [
  { name: "Shri Mani A", party: "Dravida Munnetra Kazhagam", constituency: "Dharmapuri", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Raja A", party: "Dravida Munnetra Kazhagam", constituency: "Nilgiris (SC)", state: "Tamil Nadu", status: "Sitting", terms: "11,13,14,15,17,18" },
  { name: "Shri Brijmohan Agrawal", party: "Bharatiya Janata Party", constituency: "Raipur", state: "Chhattisgarh", status: "Sitting", terms: "18" },
  { name: "Shri Damodar Agrawal", party: "Bharatiya Janata Party", constituency: "Bhilwara", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Narayandas Ahirwar", party: "Samajwadi Party", constituency: "Jalaun", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Mian Altaf Ahmad", party: "Jammu and Kashmir National Conference", constituency: "Anantnag-Rajouri", state: "Jammu and Kashmir", status: "Sitting", terms: "18" },
  { name: "Smt. Sajda Ahmed", party: "All India Trinamool Congress", constituency: "Uluberia", state: "West Bengal", status: "Sitting", terms: "16,17,18" },
  { name: "Dr. Angomcha Bimol Akoijam", party: "Indian National Congress", constituency: "Inner Manipur", state: "Manipur", status: "Sitting", terms: "18" },
  { name: "Smt. Lovely Anand", party: "Janata Dal (United)", constituency: "Sheohar", state: "Bihar", status: "Sitting", terms: "10,18" },
  { name: "Thiru D M Kathir Anand", party: "Dravida Munnetra Kazhagam", constituency: "Vellore", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Shri C N Annadurai", party: "Dravida Munnetra Kazhagam", constituency: "Tiruvannamalai", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Shri Afzal Ansari", party: "Samajwadi Party", constituency: "Ghazipur", state: "Uttar Pradesh", status: "Sitting", terms: "14,17,18" },
  { name: "Shri Anto Antony", party: "Indian National Congress", constituency: "Pathanamthitta", state: "Kerala", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Tariq Anwar", party: "Indian National Congress", constituency: "Katihar", state: "Bihar", status: "Sitting", terms: "7,8,11,12,16,18" },
  { name: "Shri Alfred Kanngam S Arthur", party: "Indian National Congress", constituency: "Outer Manipur (ST)", state: "Manipur", status: "Sitting", terms: "18" },
  { name: "Smt. D K Aruna", party: "Bharatiya Janata Party", constituency: "Mahbubnagar", state: "Telangana", status: "Sitting", terms: "18" },
  { name: "Shri Bhumare Sandipanrao Asaram", party: "Shiv Sena", constituency: "Aurangabad", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Gurjeet Singh Aujla", party: "Indian National Congress", constituency: "Amritsar", state: "Punjab", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Ramesh Awasthi", party: "Bharatiya Janata Party", constituency: "Kanpur", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Manickam Tagore B", party: "Indian National Congress", constituency: "Virudhunagar", state: "Tamil Nadu", status: "Sitting", terms: "15,17,18" },
  { name: "Shri T R Baalu", party: "Dravida Munnetra Kazhagam", constituency: "Sriperumbudur", state: "Tamil Nadu", status: "Sitting", terms: "11,12,13,14,15,17,18" },
  { name: "Shri M Mallesh Babu", party: "Janata Dal (Secular)", constituency: "Kolar (SC)", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Patel Umeshbhai Babubhai", party: "Independent", constituency: "Daman and Diu (ST)", state: "Dadra and Nagar Haveli and Daman and Diu", status: "Sitting", terms: "18" },
  { name: "Smt. Harsimrat Kaur Badal", party: "Shiromani Akali Dal", constituency: "Bathinda", state: "Punjab", status: "Sitting", terms: "15,16,17,18" },
  { name: "Prof. S P Singh Baghel", party: "Bharatiya Janata Party", constituency: "Agra", state: "Uttar Pradesh", status: "Sitting", terms: "12,13,14,17,18" },
  { name: "Shri Vijay Baghel", party: "Bharatiya Janata Party", constituency: "Durg", state: "Chhattisgarh", status: "Sitting", terms: "17,18" },
  { name: "Shri G M Harish Balayogi", party: "Telugu Desam Party", constituency: "Amalapuram", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Anil Baluni", party: "Bharatiya Janata Party", constituency: "Garhwal", state: "Uttarakhand", status: "Sitting", terms: "18" },
  { name: "Smt. Nimuben Jayantibhai Bambhaniya", party: "Bharatiya Janata Party", constituency: "Bhavnagar", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Shri Sudip Bandyopadhyay", party: "All India Trinamool Congress", constituency: "Kolkata Uttar", state: "West Bengal", status: "Sitting", terms: "12,13,15,16,17,18" },
  { name: "Shri Abhishek Banerjee", party: "All India Trinamool Congress", constituency: "Diamond Harbour", state: "West Bengal", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Kalyan Banerjee", party: "All India Trinamool Congress", constituency: "Sreerampur", state: "West Bengal", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Prasun Banerjee", party: "All India Trinamool Congress", constituency: "Howrah", state: "West Bengal", status: "Sitting", terms: "15,16,17,18" },
  { name: "Smt. Rachna Banerjee", party: "All India Trinamool Congress", constituency: "Hooghly", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Aashtikar Patil Nagesh Bapurao", party: "Shiv Sena (Uddhav Balasaheb Thackrey)", constituency: "Hingoli", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Smt. Shobhanaben Mahendrasinh Baraiya", party: "Bharatiya Janata Party", constituency: "Sabarkantha", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Shri Shrirang Appa Chandu Barne", party: "Shiv Sena", constituency: "Maval", state: "Maharashtra", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Pradan Baruah", party: "Bharatiya Janata Party", constituency: "Lakhimpur", state: "Assam", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Shyamkumar Daulat Barve", party: "Indian National Congress", constituency: "Ramtek (SC)", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri E T Mohammed Basheer", party: "Indian Union Muslim League", constituency: "Malappuram", state: "Kerala", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Joyanta Basumatary", party: "United Peoples Party, Liberal", constituency: "Kokrajhar (ST)", state: "Assam", status: "Sitting", terms: "18" },
  { name: "Shri Jagadish Chandra Barma Basunia", party: "All India Trinamool Congress", constituency: "Coochbehar (SC)", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Benny Behanan", party: "Indian National Congress", constituency: "Chalakudy", state: "Kerala", status: "Sitting", terms: "17,18" },
  { name: "Dr. Rabindra Narayan Behera", party: "Bharatiya Janata Party", constituency: "Jajpur (SC)", state: "Odisha", status: "Sitting", terms: "18" },
  { name: "Shri Hanuman Beniwal", party: "Rashtriya Loktantrik Party", constituency: "Nagaur", state: "Rajasthan", status: "Sitting", terms: "17,18" },
  { name: "Shri Ummeda Ram Beniwal", party: "Indian National Congress", constituency: "Barmer", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Jaswantsinh Sumanbhai Bhabhor", party: "Bharatiya Janata Party", constituency: "Dahod (ST)", state: "Gujarat", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Anand Bhadauria", party: "Samajwadi Party", constituency: "Dhaurahra", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Bhaskar Murlidhar Bhagare", party: "Nationalist Congress Party - Sharadchandra Pawar", constituency: "Dindori (ST)", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Sukhdeo Bhagat", party: "Indian National Congress", constituency: "Lohardaga (ST)", state: "Jharkhand", status: "Sitting", terms: "18" },
  { name: "Dr. Rajeev Bharadwaj", party: "Bharatiya Janata Party", constituency: "Kangra", state: "Himachal Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Arun Bharti", party: "Lok Jan Shakti Party (Ram Vilas)", constituency: "Jamui (SC)", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Smt. Misha Bharti", party: "Rashtriya Janata Dal", constituency: "Pataliputra", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Shri Ajay Bhatt", party: "Bharatiya Janata Party", constituency: "Nainital-Udhamsingh Nagar", state: "Uttarakhand", status: "Sitting", terms: "17,18" },
  { name: "Chh. Udayanraje Pratapsinha Maharaj Bhonsle", party: "Bharatiya Janata Party", constituency: "Satara", state: "Maharashtra", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Partha Bhowmick", party: "All India Trinamool Congress", constituency: "Barrackpur", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Srinivasa Varma B J P Varma Bhupathiraju", party: "Bharatiya Janata Party", constituency: "Narsapuram", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Ramvir Singh Bidhuri", party: "Bharatiya Janata Party", constituency: "South Delhi", state: "NCT of Delhi", status: "Sitting", terms: "18" },
  { name: "Dr. Vinod Kumar Bind", party: "Bharatiya Janata Party", constituency: "Bhadohi", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Om Birla", party: "Bharatiya Janata Party", constituency: "Kota", state: "Rajasthan", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Raju Bista", party: "Bharatiya Janata Party", constituency: "Darjeeling", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Shri Basavaraj Bommai", party: "Bharatiya Janata Party", constituency: "Haveri", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Sunil Bose", party: "Indian National Congress", constituency: "Chamarajanagar (SC)", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Satpal Brahamchari", party: "Indian National Congress", constituency: "Sonipat", state: "Haryana", status: "Sitting", terms: "18" },
  { name: "Shri Robert Bruce C", party: "Indian National Congress", constituency: "Tirunelveli", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Dr. Raj Kumar Chabbewal", party: "Aam Aadmi Party", constituency: "Hoshiarpur (SC)", state: "Punjab", status: "Sitting", terms: "18" },
  { name: "Shri Rajkumar Chahar", party: "Bharatiya Janata Party", constituency: "Fatehpur Sikri", state: "Uttar Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Arup Chakraborty", party: "All India Trinamool Congress", constituency: "Bankura", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Gaddigoudar Parvatagouda Chandanagouda", party: "Bharatiya Janata Party", constituency: "Bagalkot", state: "Karnataka", status: "Sitting", terms: "14,15,16,17,18" },
  { name: "Shri Yogender Chandolia", party: "Bharatiya Janata Party", constituency: "North West Delhi (SC)", state: "NCT of Delhi", status: "Sitting", terms: "18" },
  { name: "Shri Charanjit Singh Channi", party: "Indian National Congress", constituency: "Jalandhar (SC)", state: "Punjab", status: "Sitting", terms: "18" },
  { name: "Shri P P Chaudhary", party: "Bharatiya Janata Party", constituency: "Pali", state: "Rajasthan", status: "Sitting", terms: "16,17,18" },
  { name: "Shri R K Chaudhary", party: "Samajwadi Party", constituency: "Mohanlalganj", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Ram Prasad Chaudhary", party: "Samajwadi Party", constituency: "Basti", state: "Uttar Pradesh", status: "Sitting", terms: "9,18" },
  { name: "Shri Varun Chaudhry", party: "Indian National Congress", constituency: "Ambala (SC)", state: "Haryana", status: "Sitting", terms: "18" },
  { name: "Shri Chandan Chauhan", party: "Rashtriya Lok Dal", constituency: "Bijnor", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Devusinh Chauhan", party: "Bharatiya Janata Party", constituency: "Kheda", state: "Gujarat", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Shahu Shahaji Chhatrapati", party: "Indian National Congress", constituency: "Kolhapur", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Chhotelal", party: "Samajwadi Party", constituency: "Robertsganj", state: "Uttar Pradesh", status: "Sitting", terms: "16,18" },
  { name: "Shri Karti P Chidambaram", party: "Indian National Congress", constituency: "Sivaganga", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Dr. Raj Bhushan Choudhary", party: "Bharatiya Janata Party", constituency: "Muzaffarpur", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Ms Iqra Choudhary", party: "Samajwadi Party", constituency: "Kairana", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Bhagirath Choudhary", party: "Bharatiya Janata Party", constituency: "Ajmer", state: "Rajasthan", status: "Sitting", terms: "17,18" },
  { name: "Shri Chandra Prakash Choudhary", party: "AJSU Party", constituency: "Giridih", state: "Jharkhand", status: "Sitting", terms: "17,18" },
  { name: "Shri Darshan Singh Choudhary", party: "Bharatiya Janata Party", constituency: "Hoshangabad", state: "Madhya Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Lumbaram Choudhary", party: "Bharatiya Janata Party", constituency: "Jalore", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Pankaj Choudhary", party: "Bharatiya Janata Party", constituency: "Maharajganj", state: "Uttar Pradesh", status: "Sitting", terms: "10,11,12,14,16,17,18" },
  { name: "Smt. Roopkumari Choudhary", party: "Bharatiya Janata Party", constituency: "Mahasamund", state: "Chhattisgarh", status: "Sitting", terms: "18" },
  { name: "Shri Isha Khan Choudhury", party: "Indian National Congress", constituency: "Maldaha Dakshin", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Phani Bhusan Choudhury", party: "Asom Gana Parishad", constituency: "Barpeta", state: "Assam", status: "Sitting", terms: "18" },
  { name: "Shri Shivraj Singh Chouhan", party: "Bharatiya Janata Party", constituency: "Vidisha", state: "Madhya Pradesh", status: "Sitting", terms: "10,11,12,13,14,18" },
  { name: "Smt. Anita Nagarsingh Chouhan", party: "Bharatiya Janata Party", constituency: "Ratlam (ST)", state: "Madhya Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Captain Brijesh Chowta", party: "Bharatiya Janata Party", constituency: "Dakshina Kannada", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Rajesh Naranbhai Chudasama", party: "Bharatiya Janata Party", constituency: "Junagadh", state: "Gujarat", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Malaiyarasan D", party: "Dravida Munnetra Kazhagam", constituency: "Kallakurichi", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Bharatsinhji Shankarji Dabhi", party: "Bharatiya Janata Party", constituency: "Patan", state: "Gujarat", status: "Sitting", terms: "17,18" },
  { name: "Shri Mukeshkumar Chandrakaant Dalal", party: "Bharatiya Janata Party", constituency: "Surat", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Dr. Kakoli Ghosh Dastidar", party: "All India Trinamool Congress", constituency: "Barasat", state: "West Bengal", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Tatkare Sunil Dattatrey", party: "Nationalist Congress Party", constituency: "Raigad", state: "Maharashtra", status: "Sitting", terms: "17,18" },
  { name: "Shri Biplab Kumar Deb", party: "Bharatiya Janata Party", constituency: "Tripura West", state: "Tripura", status: "Sitting", terms: "18" },
  { name: "Smt. Kriti Devi Debbarman", party: "Bharatiya Janata Party", constituency: "Tripura East (ST)", state: "Tripura", status: "Sitting", terms: "18" },
  { name: "Smt. Sangeeta Kumari Singh Deo", party: "Bharatiya Janata Party", constituency: "Bolangir", state: "Odisha", status: "Sitting", terms: "12,13,14,17,18" },
  { name: "Shri Anil Yeshwant Desai", party: "Shiv Sena (Uddhav Balasaheb Thackrey)", constituency: "Mumbai South Central", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Sanjay Uttamrao Deshmukh", party: "Shiv Sena (Uddhav Balasaheb Thackrey)", constituency: "Yavatmal-Washim", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Adhikari Deepak Dev", party: "All India Trinamool Congress", constituency: "Ghatal", state: "West Bengal", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Lavu Sri Krishna Devarayalu", party: "Telugu Desam Party", constituency: "Narasaraopet", state: "Andhra Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Smt. Annpurna Devi", party: "Bharatiya Janata Party", constituency: "Kodarma", state: "Jharkhand", status: "Sitting", terms: "17,18" },
  { name: "Smt. Malvika Devi", party: "Bharatiya Janata Party", constituency: "Kalahandi", state: "Odisha", status: "Sitting", terms: "18" },
  { name: "Smt. Veena Devi", party: "Lok Jan Shakti Party (Ram Vilas)", constituency: "Vaishali", state: "Bihar", status: "Sitting", terms: "17,18" },
  { name: "Smt. Vijaylakshmi Devi", party: "Janata Dal (United)", constituency: "Siwan", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Shri Arvind Dharmapuri", party: "Bharatiya Janata Party", constituency: "Nizamabad", state: "Telangana", status: "Sitting", terms: "17,18" },
  { name: "Shri Anup Sanjay Dhotre", party: "Bharatiya Janata Party", constituency: "Akola", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Dr. Bachhav Shobha Dinesh", party: "Indian National Congress", constituency: "Dhule", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Jitendra Kumar Dohare", party: "Samajwadi Party", constituency: "Etawah", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Dr. Nishikant Dubey", party: "Bharatiya Janata Party", constituency: "Godda", state: "Jharkhand", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Ashish Dubey", party: "Bharatiya Janata Party", constituency: "Jabalpur", state: "Madhya Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Vijay Kumar Dubey", party: "Bharatiya Janata Party", constituency: "Kushi Nagar", state: "Uttar Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Ranjit Dutta", party: "Bharatiya Janata Party", constituency: "Sonitpur", state: "Assam", status: "Sitting", terms: "18" },
  { name: "Shri Hibi Eden", party: "Indian National Congress", constituency: "Ernakulam", state: "Kerala", status: "Sitting", terms: "17,18" },
  { name: "Shri Captain Viriato Fernandes", party: "Indian National Congress", constituency: "South Goa", state: "Goa", status: "Sitting", terms: "18" },
  { name: "Shri Anil Firojiya", party: "Bharatiya Janata Party", constituency: "Ujjain (SC)", state: "Madhya Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Selvam G", party: "Dravida Munnetra Kazhagam", constituency: "Kancheepuram (SC)", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Shri Vamsi Krishna Gaddam", party: "Indian National Congress", constituency: "Peddapalle (SC)", state: "Telangana", status: "Sitting", terms: "18" },
  { name: "Shri Nitin Jairam Gadkari", party: "Bharatiya Janata Party", constituency: "Nagpur", state: "Maharashtra", status: "Sitting", terms: "16,17,18" },
  { name: "Prof. Varsha Eknath Gaikwad", party: "Indian National Congress", constituency: "Mumbai North Central", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Dr. Dharamvira Gandhi", party: "Indian National Congress", constituency: "Patiala", state: "Punjab", status: "Sitting", terms: "16,18" },
  { name: "Shri Rahul Gandhi", party: "Indian National Congress", constituency: "Rae Bareli", state: "Uttar Pradesh", status: "Sitting", terms: "14,15,16,17,18" },
  { name: "Shri Abhijit Gangopadhyay", party: "Bharatiya Janata Party", constituency: "Tamluk", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Chhatrapal Singh Gangwar", party: "Bharatiya Janata Party", constituency: "Bareilly", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Tapir Gao", party: "Bharatiya Janata Party", constituency: "Arunachal East", state: "Arunachal Pradesh", status: "Sitting", terms: "14,17,18" },
  { name: "Shri Atul Garg", party: "Bharatiya Janata Party", constituency: "Ghaziabad", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Satish Kumar Gautam", party: "Bharatiya Janata Party", constituency: "Aligarh", state: "Uttar Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Adv K. Francis George", party: "Kerala Congress", constituency: "Kottayam", state: "Kerala", status: "Sitting", terms: "13,14,18" },
  { name: "Ms Sayani Ghosh", party: "All India Trinamool Congress", constituency: "Jadavpur", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Sher Singh Ghubaya", party: "Indian National Congress", constituency: "Firozpur", state: "Punjab", status: "Sitting", terms: "15,16,18" },
  { name: "Shri Gaurav Gogoi", party: "Indian National Congress", constituency: "Jorhat", state: "Assam", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Suresh Gopi", party: "Bharatiya Janata Party", constituency: "Thrissur", state: "Kerala", status: "Sitting", terms: "18" },
  { name: "Shri K Gopinath", party: "Indian National Congress", constituency: "Krishnagiri", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Arun Govil", party: "Bharatiya Janata Party", constituency: "Meerut", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Piyush Vedprakash Goyal", party: "Bharatiya Janata Party", constituency: "Mumbai North", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Sudheer Gupta", party: "Bharatiya Janata Party", constituency: "Mandsour", state: "Madhya Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Krishan Pal Gurjar", party: "Bharatiya Janata Party", constituency: "Faridabad", state: "Haryana", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Maddila Gurumoorthy", party: "Yuvajana Sramika Rythu Congress Party", constituency: "Tirupati (SC)", state: "Andhra Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Bapi Haldar", party: "All India Trinamool Congress", constituency: "Mathurapur (SC)", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Mohmad Haneefa", party: "Independent", constituency: "Ladakh", state: "Ladakh", status: "Sitting", terms: "18" },
  { name: "Shri Vijay Kumar Hansdak", party: "Jharkhand Mukti Morcha", constituency: "Rajmahal (ST)", state: "Jharkhand", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Gurmeet Singh Meet Hayer", party: "Aam Aadmi Party", constituency: "Sangrur", state: "Punjab", status: "Sitting", terms: "18" },
  { name: "Shri K Rajashekar Basavaraj Hitnal", party: "Indian National Congress", constituency: "Koppal", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Deepender Singh Hooda", party: "Indian National Congress", constituency: "Rohtak", state: "Haryana", status: "Sitting", terms: "14,15,16,18" },
  { name: "Md. Rakibul Hussain", party: "Indian National Congress", constituency: "Dhubri", state: "Assam", status: "Sitting", terms: "18" },
  { name: "Shri Kuldeep Indora", party: "Indian National Congress", constituency: "Ganganagar (SC)", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Rajpalsinh Mahendrasinh Jadav", party: "Bharatiya Janata Party", constituency: "Panchmahal", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Shri Prataprao Ganpatrao Jadhav", party: "Shiv Sena", constituency: "Buldhana", state: "Maharashtra", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Sanjay Haribhau Jadhav", party: "Shiv Sena (Uddhav Balasaheb Thackrey)", constituency: "Parbhani", state: "Maharashtra", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Dr. S Jagathratchakan", party: "Dravida Munnetra Kazhagam", constituency: "Arakkonam", state: "Tamil Nadu", status: "Sitting", terms: "8,13,15,17,18" },
  { name: "Dr. Sanjay Jaiswal", party: "Bharatiya Janata Party", constituency: "Paschim Champaran", state: "Bihar", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Manish Jaiswal", party: "Bharatiya Janata Party", constituency: "Hazaribagh", state: "Jharkhand", status: "Sitting", terms: "18" },
  { name: "Shri S Supongmeren Jamir", party: "Indian National Congress", constituency: "Nagaland", state: "Nagaland", status: "Sitting", terms: "18" },
  { name: "Smt. Kamlesh Jangde", party: "Bharatiya Janata Party", constituency: "Janjgir-Champa (SC)", state: "Chhattisgarh", status: "Sitting", terms: "18" },
  { name: "Km. Priyanka Satish Jarkiholi", party: "Indian National Congress", constituency: "Chikkodi", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Bhajan Lal Jatav", party: "Indian National Congress", constituency: "Karauli-Dholpur (SC)", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Smt. Sanjna Jatav", party: "Indian National Congress", constituency: "Bharatpur (SC)", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Dr. Mohammad Jawed", party: "Indian National Congress", constituency: "Kishanganj", state: "Bihar", status: "Sitting", terms: "17,18" },
  { name: "Shri Azad Kirti Jha", party: "All India Trinamool Congress", constituency: "Bardhaman-Durgapur", state: "West Bengal", status: "Sitting", terms: "13,15,16,18" },
  { name: "Shri Ramesh Chandappa Jigajinagi", party: "Bharatiya Janata Party", constituency: "Bijapur (SC)", state: "Karnataka", status: "Sitting", terms: "12,13,14,15,16,17,18" },
  { name: "Shri Naveen Jindal", party: "Bharatiya Janata Party", constituency: "Kurukshetra", state: "Haryana", status: "Sitting", terms: "14,15,18" },
  { name: "Dr. Hemang Joshi", party: "Bharatiya Janata Party", constituency: "Vadodara", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Shri Chandra Prakash Joshi", party: "Bharatiya Janata Party", constituency: "Chittorgarh", state: "Rajasthan", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Pralhad Joshi", party: "Bharatiya Janata Party", constituency: "Dharwad", state: "Karnataka", status: "Sitting", terms: "14,15,16,17,18" },
  { name: "Ms. S Jothimani", party: "Indian National Congress", constituency: "Karur", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Shri Eswarasamy K", party: "Dravida Munnetra Kazhagam", constituency: "Pollachi", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Navaskani K", party: "Indian Union Muslim League", constituency: "Ramanathapuram", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Shri Subbarayan K", party: "Communist Party of India", constituency: "Tiruppur", state: "Tamil Nadu", status: "Sitting", terms: "14,17,18" },
  { name: "Shri Vishweshwar Hegde Kageri", party: "Bharatiya Janata Party", constituency: "Uttara Kannada", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Dr. Kalyan Vaijinathrao Kale", party: "Indian National Congress", constituency: "Jalna", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Amar Sharadrao Kale", party: "Nationalist Congress Party - Sharadchandra Pawar", constituency: "Wardha", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Dr. Shivaji Bandappa Kalge", party: "Indian National Congress", constituency: "Latur (SC)", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Appalanaidu Kalisetti", party: "Telugu Desam Party", constituency: "Vizianagaram", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Dileshwar Kamait", party: "Janata Dal (United)", constituency: "Supaul", state: "Bihar", status: "Sitting", terms: "17,18" },
  { name: "Shri Malvinder Singh Kang", party: "Aam Aadmi Party", constituency: "Anandpur Sahib", state: "Punjab", status: "Sitting", terms: "18" },
  { name: "Km. Shobha Karandlaje", party: "Bharatiya Janata Party", constituency: "Bangalore North", state: "Karnataka", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Govind Makthappa Karjol", party: "Bharatiya Janata Party", constituency: "Chitradurga (SC)", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Smt. Kanimozhi Karunanidhi", party: "Dravida Munnetra Kazhagam", constituency: "Thoothukkudi", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Shri Mahesh Kashyap", party: "Bharatiya Janata Party", constituency: "Bastar (ST)", state: "Chhattisgarh", status: "Sitting", terms: "18" },
  { name: "Shri Suresh Kumar Kashyap", party: "Bharatiya Janata Party", constituency: "Shimla (SC)", state: "Himachal Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Rahul Kaswan", party: "Indian National Congress", constituency: "Churu", state: "Rajasthan", status: "Sitting", terms: "16,17,18" },
  { name: "Dr. Kadiyam Kavya", party: "Indian National Congress", constituency: "Warangal (SC)", state: "Telangana", status: "Sitting", terms: "18" },
  { name: "Smt. Raksha Nikhil Khadse", party: "Bharatiya Janata Party", constituency: "Raver", state: "Maharashtra", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Sarabjeet Singh Khalsa", party: "Independent", constituency: "Faridkot (SC)", state: "Punjab", status: "Sitting", terms: "18" },
  { name: "Md Abu Taher Khan", party: "All India Trinamool Congress", constituency: "Murshidabad", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Shri Saumitra Khan", party: "Bharatiya Janata Party", constituency: "Bishnupur (SC)", state: "West Bengal", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Praveen Khandelwal", party: "Bharatiya Janata Party", constituency: "Chandni Chowk", state: "NCT of Delhi", status: "Sitting", terms: "18" },
  { name: "Shri Sagar Eshwar Khandre", party: "Indian National Congress", constituency: "Bidar", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Kalipada Saren Kherwal", party: "All India Trinamool Congress", constituency: "Jhargram (ST)", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Ravindra Shukla Alias Ravi Kishan", party: "Bharatiya Janata Party", constituency: "Gorakhpur", state: "Uttar Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Jugal Kishore", party: "Bharatiya Janata Party", constituency: "Jammu", state: "Jammu and Kashmir", status: "Sitting", terms: "16,17,18" },
  { name: "Dr. Amol Ramsing Kolhe", party: "Nationalist Congress Party - Sharadchandra Pawar", constituency: "Shirur", state: "Maharashtra", status: "Sitting", terms: "17,18" },
  { name: "Dr. Faggan Singh Kulaste", party: "Bharatiya Janata Party", constituency: "Mandla (ST)", state: "Madhya Pradesh", status: "Sitting", terms: "11,12,13,14,16,17,18" },
  { name: "Dr. Anand Kumar", party: "Bharatiya Janata Party", constituency: "Bahraich", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Dr. D Ravi Kumar", party: "Viduthalai Chiruthaigal Katchi", constituency: "Viluppuram (SC)", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Dr. Virendra Kumar", party: "Bharatiya Janata Party", constituency: "Tikamgarh (SC)", state: "Madhya Pradesh", status: "Sitting", terms: "11,12,13,14,15,16,17,18" },
  { name: "Shri Bandi Sanjay Kumar", party: "Bharatiya Janata Party", constituency: "Karimnagar", state: "Telangana", status: "Sitting", terms: "17,18" },
  { name: "Shri Kaushalendra Kumar", party: "Janata Dal (United)", constituency: "Nalanda", state: "Bihar", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Manoj Kumar", party: "Indian National Congress", constituency: "Sasaram (SC)", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Shri Putta Mahesh Kumar", party: "Telugu Desam Party", constituency: "Eluru", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Sunil Kumar", party: "Janata Dal (United)", constituency: "Valmiki Nagar", state: "Bihar", status: "Sitting", terms: "17,18" },
  { name: "Shri H D Kumaraswamy", party: "Janata Dal (Secular)", constituency: "Mandya", state: "Karnataka", status: "Sitting", terms: "11,15,18" },
  { name: "Kumari Selja", party: "Indian National Congress", constituency: "Sirsa (SC)", state: "Haryana", status: "Sitting", terms: "10,11,14,15,18" },
  { name: "Adv Dean Kuriakose", party: "Indian National Congress", constituency: "Idukki", state: "Kerala", status: "Sitting", terms: "17,18" },
  { name: "Shri Bharat Singh Kushwah", party: "Bharatiya Janata Party", constituency: "Gwalior", state: "Madhya Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Babu Singh Kushwaha", party: "Samajwadi Party", constituency: "Jaunpur", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Chavda Vinod Lakhamshi", party: "Bharatiya Janata Party", constituency: "Kachchh (SC)", state: "Gujarat", status: "Sitting", terms: "16,17,18" },
  { name: "Shri G Lakshminarayana", party: "Telugu Desam Party", constituency: "Anantapur", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Kishori Lal", party: "Indian National Congress", constituency: "Amethi", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Manohar Lal", party: "Bharatiya Janata Party", constituency: "Karnal", state: "Haryana", status: "Sitting", terms: "18" },
  { name: "Shri Shankar Lalwani", party: "Bharatiya Janata Party", constituency: "Indore", state: "Madhya Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Nilesh Dnyandev Lanke", party: "Nationalist Congress Party - Sharadchandra Pawar", constituency: "Ahmednagar", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Ajendra Singh Lodhi", party: "Samajwadi Party", constituency: "Hamirpur", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Rahul Singh Lodhi", party: "Bharatiya Janata Party", constituency: "Damoh", state: "Madhya Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Tharaniventhan M S", party: "Dravida Munnetra Kazhagam", constituency: "Arani", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Smt. Poonamben Hematbhai Maadam", party: "Bharatiya Janata Party", constituency: "Jamnagar", state: "Gujarat", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Utkarsh Verma Madhur", party: "Samajwadi Party", constituency: "Kheri", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Smt. Jyotsna Charandas Mahant", party: "Indian National Congress", constituency: "Korba", state: "Chhattisgarh", status: "Sitting", terms: "17,18" },
  { name: "Shri Chintamani Maharaj", party: "Bharatiya Janata Party", constituency: "Surguja (ST)", state: "Chhattisgarh", status: "Sitting", terms: "18" },
  { name: "Shri Bidyut Baran Mahato", party: "Bharatiya Janata Party", constituency: "Jamshedpur", state: "Jharkhand", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Dulu Mahato", party: "Bharatiya Janata Party", constituency: "Dhanbad", state: "Jharkhand", status: "Sitting", terms: "18" },
  { name: "Shri Jyotirmay Singh Mahato", party: "Bharatiya Janata Party", constituency: "Purulia", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Shri Bhartruhari Mahtab", party: "Bharatiya Janata Party", constituency: "Cuttack", state: "Odisha", status: "Sitting", terms: "12,13,14,15,16,17,18" },
  { name: "Shri Balabhadra Majhi", party: "Bharatiya Janata Party", constituency: "Nabarangpur (ST)", state: "Odisha", status: "Sitting", terms: "16,18" },
  { name: "Shri Naba Charan Majhi", party: "Bharatiya Janata Party", constituency: "Mayurbhanj (ST)", state: "Odisha", status: "Sitting", terms: "18" },
  { name: "Smt. Joba Majhi", party: "Jharkhand Mukti Morcha", constituency: "Singhbhum (ST)", state: "Jharkhand", status: "Sitting", terms: "18" },
  { name: "Dr. Sukanta Majumdar", party: "Bharatiya Janata Party", constituency: "Balurghat", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Shri Dineshbhai Makwana", party: "Bharatiya Janata Party", constituency: "Ahmedabad West (SC)", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Shri Asit Kumar Mal", party: "All India Trinamool Congress", constituency: "Bolpur (SC)", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Shri Harsh Malhotra", party: "Bharatiya Janata Party", constituency: "East Delhi", state: "NCT of Delhi", status: "Sitting", terms: "18" },
  { name: "Smt. June Maliah", party: "All India Trinamool Congress", constituency: "Medinipur", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Harendra Singh Malik", party: "Samajwadi Party", constituency: "Muzaffarnagar", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Smt. Hema Malini", party: "Bharatiya Janata Party", constituency: "Mathura", state: "Uttar Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Kripanath Mallah", party: "Bharatiya Janata Party", constituency: "Karimganj", state: "Assam", status: "Sitting", terms: "17,18" },
  { name: "Dr. Prabha Mallikarjun", party: "Indian National Congress", constituency: "Davanagere", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Ajay Kumar Mandal", party: "Janata Dal (United)", constituency: "Bhagalpur", state: "Bihar", status: "Sitting", terms: "17,18" },
  { name: "Shri Ramprit Mandal", party: "Janata Dal (United)", constituency: "Jhanjharpur", state: "Bihar", status: "Sitting", terms: "17,18" },
  { name: "Dr. Mansukh Mandaviya", party: "Bharatiya Janata Party", constituency: "Porbandar", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Shri Dhairyasheel Sambhajirao Mane", party: "Shiv Sena", constituency: "Hatkanangle", state: "Maharashtra", status: "Sitting", terms: "17,18" },
  { name: "Shri Shashank Mani", party: "Bharatiya Janata Party", constituency: "Deoria", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Jitan Ram Manjhi", party: "Hindustani Awam Morcha (Secular)", constituency: "Gaya (SC)", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Dr. C N Manjunath", party: "Bharatiya Janata Party", constituency: "Bangalore Rural", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Thiru Dayanidhi Maran", party: "Dravida Munnetra Kazhagam", constituency: "Chennai Central", state: "Tamil Nadu", status: "Sitting", terms: "14,15,17,18" },
  { name: "Shri Imran Masood", party: "Indian National Congress", constituency: "Saharanpur", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Sribharat Mathukumilli", party: "Telugu Desam Party", constituency: "Visakhapatnam", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Neeraj Maurya", party: "Samajwadi Party", constituency: "Aonla", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Smt. Bijuli Kalita Medhi", party: "Bharatiya Janata Party", constituency: "Guwahati", state: "Assam", status: "Sitting", terms: "18" },
  { name: "Shri Harish Chandra Meena", party: "Indian National Congress", constituency: "Tonk-Sawai Madhopur", state: "Rajasthan", status: "Sitting", terms: "16,18" },
  { name: "Shri Murari Lal Meena", party: "Indian National Congress", constituency: "Dausa (ST)", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Arjun Ram Meghwal", party: "Bharatiya Janata Party", constituency: "Bikaner (SC)", state: "Rajasthan", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Aga Syed Ruhullah Mehdi", party: "Jammu and Kashmir National Conference", constituency: "Srinagar", state: "Jammu and Kashmir", status: "Sitting", terms: "18" },
  { name: "Smt. Mahima Kumari Mewar", party: "Bharatiya Janata Party", constituency: "Rajsamand", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Naresh Ganpat Mhaske", party: "Shiv Sena", constituency: "Thane", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Balya Mama Suresh Gopinath Mhatre", party: "Nationalist Congress Party - Sharadchandra Pawar", constituency: "Bhiwandi", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Dr. Rajesh Mishra", party: "Bharatiya Janata Party", constituency: "Sidhi", state: "Madhya Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Janardan Mishra", party: "Bharatiya Janata Party", constituency: "Rewa", state: "Madhya Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Smt. Bag Mitali", party: "All India Trinamool Congress", constituency: "Arambag (SC)", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Narendra Modi", party: "Bharatiya Janata Party", constituency: "Varanasi", state: "Uttar Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Shri P C Mohan", party: "Bharatiya Janata Party", constituency: "Bangalore Central", state: "Karnataka", status: "Sitting", terms: "15,16,17,18" },
  { name: "Smt. Delkar Kalaben Mohanbhai", party: "Bharatiya Janata Party", constituency: "Dadra and Nagar Haveli", state: "Dadra and Nagar Haveli and Daman and Diu", status: "Sitting", terms: "17,18" },
  { name: "Shri Murlidhar Mohol", party: "Bharatiya Janata Party", constituency: "Pune", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Ms. Mahua Moitra", party: "All India Trinamool Congress", constituency: "Krishnanagar", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Smt. Pratima Mondal", party: "All India Trinamool Congress", constituency: "Jaynagar (SC)", state: "West Bengal", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Kali Charan Munda", party: "Indian National Congress", constituency: "Khunti (ST)", state: "Jharkhand", status: "Sitting", terms: "18" },
  { name: "Shri Khagen Murmu", party: "Bharatiya Janata Party", constituency: "Maldaha Uttar", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Shri Bhojraj Nag", party: "Bharatiya Janata Party", constituency: "Kanker (ST)", state: "Chhattisgarh", status: "Sitting", terms: "18" },
  { name: "Shri Rodmal Nagar", party: "Bharatiya Janata Party", constituency: "Rajgarh", state: "Madhya Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Bastipati Nagaraju", party: "Telugu Desam Party", constituency: "Kurnool", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Godam Nagesh", party: "Bharatiya Janata Party", constituency: "Adilabad (ST)", state: "Telangana", status: "Sitting", terms: "16,18" },
  { name: "Shri Kinjarapu Rammohan Naidu", party: "Telugu Desam Party", constituency: "Srikakulam", state: "Andhra Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Shri G Kumar Naik", party: "Indian National Congress", constituency: "Raichur (ST)", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Shripad Yesso Naik", party: "Bharatiya Janata Party", constituency: "North Goa", state: "Goa", status: "Sitting", terms: "13,14,15,16,17,18" },
  { name: "Dr. Kirsan Namdeo", party: "Indian National Congress", constituency: "Gadchiroli-Chimur (ST)", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Ananta Nayak", party: "Bharatiya Janata Party", constituency: "Keonjhar (ST)", state: "Odisha", status: "Sitting", terms: "13,14,18" },
  { name: "Thiru Arun Nehru", party: "Dravida Munnetra Kazhagam", constituency: "Perambalur", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Laxmikant Pappu Nishad", party: "Samajwadi Party", constituency: "Sant Kabir Nagar", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Rambhual Nishad", party: "Samajwadi Party", constituency: "Sultanpur", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Brijendra Singh Ola", party: "Indian National Congress", constituency: "Jhunjhunu", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Jual Oram", party: "Bharatiya Janata Party", constituency: "Sundargarh (ST)", state: "Odisha", status: "Sitting", terms: "12,13,14,16,17,18" },
  { name: "Shri Asaduddin Owaisi", party: "All India Majlis-E-Ittehadul Muslimeen", constituency: "Hyderabad", state: "Telangana", status: "Sitting", terms: "14,15,16,17,18" },
  { name: "Dr. Ganapathy Rajkumar P", party: "Dravida Munnetra Kazhagam", constituency: "Coimbatore", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Adv Gowaal Kagada Padavi", party: "Indian National Congress", constituency: "Nandurbar (ST)", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Dr. Prashant Yadaorao Padole", party: "Indian National Congress", constituency: "Bhandara-Gondiya", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Jagdambika Pal", party: "Bharatiya Janata Party", constituency: "Domariyaganj", state: "Uttar Pradesh", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Baijayant Panda", party: "Bharatiya Janata Party", constituency: "Kendrapara", state: "Odisha", status: "Sitting", terms: "15,16,18" },
  { name: "Shri Sanatan Pandey", party: "Samajwadi Party", constituency: "Ballia", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Santosh Pandey", party: "Bharatiya Janata Party", constituency: "Rajnandgaon", state: "Chhattisgarh", status: "Sitting", terms: "17,18" },
  { name: "Shri Sukanta Kumar Panigrahi", party: "Bharatiya Janata Party", constituency: "Kandhamal", state: "Odisha", status: "Sitting", terms: "18" },
  { name: "Dr. Pradeep Kumar Panigrahy", party: "Bharatiya Janata Party", constituency: "Berhampur", state: "Odisha", status: "Sitting", terms: "18" },
  { name: "Shri Rudra Narayan Pany", party: "Bharatiya Janata Party", constituency: "Dhenkanal", state: "Odisha", status: "Sitting", terms: "18" },
  { name: "Shri Shafi Parambil", party: "Indian National Congress", constituency: "Vadakara", state: "Kerala", status: "Sitting", terms: "18" },
  { name: "Smt. Bharti Pardhi", party: "Bharatiya Janata Party", constituency: "Balaghat", state: "Madhya Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Jai Parkash", party: "Indian National Congress", constituency: "Hisar", state: "Haryana", status: "Sitting", terms: "9,11,14,18" },
  { name: "Shri B K Parthasarathi", party: "Telugu Desam Party", constituency: "Hindupur", state: "Andhra Pradesh", status: "Sitting", terms: "13,18" },
  { name: "Shri Chirag Paswan", party: "Lok Jan Shakti Party (Ram Vilas)", constituency: "Hajipur (SC)", state: "Bihar", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Kamlesh Paswan", party: "Bharatiya Janata Party", constituency: "Bansgaon", state: "Uttar Pradesh", status: "Sitting", terms: "15,16,17,18" },
  { name: "Dr. Shiv Pal Singh Patel", party: "Samajwadi Party", constituency: "Pratapgarh", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Dhaval Laxmanbhai Patel", party: "Bharatiya Janata Party", constituency: "Valsad (ST)", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Shri Gajendra Singh Patel", party: "Bharatiya Janata Party", constituency: "Khargone (ST)", state: "Madhya Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Haribhai Patel", party: "Bharatiya Janata Party", constituency: "Mahesana", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Shri Hasmukhbhai Somabhai Patel", party: "Bharatiya Janata Party", constituency: "Ahmedabad East", state: "Gujarat", status: "Sitting", terms: "17,18" },
  { name: "Shri Miteshbhai Rameshbhai Patel", party: "Bharatiya Janata Party", constituency: "Anand", state: "Gujarat", status: "Sitting", terms: "17,18" },
  { name: "Shri Naresh Chandra Uttam Patel", party: "Samajwadi Party", constituency: "Fatehpur", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Praveen Patel", party: "Bharatiya Janata Party", constituency: "Phulpur", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Shreyas M Patel", party: "Indian National Congress", constituency: "Hassan", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Smt. Anupriya Patel", party: "Apna Dal (Soneylal)", constituency: "Mirzapur", state: "Uttar Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Smt. Krishna Devi Shivshankar Patel", party: "Samajwadi Party", constituency: "Banda", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Chandrakant Raghunath Patil", party: "Bharatiya Janata Party", constituency: "Navsari", state: "Gujarat", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Gyaneshwar Patil", party: "Bharatiya Janata Party", constituency: "Khandwa", state: "Madhya Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Sanjay Dina Patil", party: "Shiv Sena (Uddhav Balasaheb Thackrey)", constituency: "Mumbai North East", state: "Maharashtra", status: "Sitting", terms: "15,18" },
  { name: "Shri Vishaldada Prakashbapu Patil", party: "Independent", constituency: "Sangli", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Dr. Sambit Patra", party: "Bharatiya Janata Party", constituency: "Puri", state: "Odisha", status: "Sitting", terms: "18" },
  { name: "Shri Kartick Chandra Paul", party: "Bharatiya Janata Party", constituency: "Raiganj", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Dr. Chandra Sekhar Pemmasani", party: "Telugu Desam Party", constituency: "Guntur", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Kota Srinivasa Poojary", party: "Bharatiya Janata Party", constituency: "Udupi Chikmagalur", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Balram Naik Porika", party: "Indian National Congress", constituency: "Mahabubabad (ST)", state: "Telangana", status: "Sitting", terms: "15,18" },
  { name: "Shri Dharmendra Pradhan", party: "Bharatiya Janata Party", constituency: "Sambalpur", state: "Odisha", status: "Sitting", terms: "14,18" },
  { name: "Adv. Adoor Prakash", party: "Indian National Congress", constituency: "Attingal", state: "Kerala", status: "Sitting", terms: "17,18" },
  { name: "Shri Jai Prakash", party: "Bharatiya Janata Party", constituency: "Hardoi", state: "Uttar Pradesh", status: "Sitting", terms: "10,11,13,14,17,18" },
  { name: "Shri K E Prakash", party: "Dravida Munnetra Kazhagam", constituency: "Erode", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Dr. M K Vishnu Prasad", party: "Indian National Congress", constituency: "Cuddalore", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Shri Awadhesh Prasad", party: "Samajwadi Party", constituency: "Faizabad", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Ravi Shankar Prasad", party: "Bharatiya Janata Party", constituency: "Patna Sahib", state: "Bihar", status: "Sitting", terms: "17,18" },
  { name: "Shri Sudama Prasad", party: "Communist Party of India (Marxist-Leninist) Liberation", constituency: "Arrah", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Shri Jitin Prasada", party: "Bharatiya Janata Party", constituency: "Pilibhit", state: "Uttar Pradesh", status: "Sitting", terms: "14,15,18" },
  { name: "Shri N K Premachandran", party: "Revolutionary Socialist Party", constituency: "Kollam", state: "Kerala", status: "Sitting", terms: "11,12,16,17,18" },
  { name: "Shri Tanuj Punia", party: "Indian National Congress", constituency: "Barabanki", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Dr. D. Purandeswari", party: "Bharatiya Janata Party", constituency: "Rajahmundry", state: "Andhra Pradesh", status: "Sitting", terms: "14,15,18" },
  { name: "Shri Pradeep Purohit", party: "Bharatiya Janata Party", constituency: "Bargarh", state: "Odisha", status: "Sitting", terms: "18" },
  { name: "Km. Sudha R", party: "Indian National Congress", constituency: "Mayiladuthurai", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Sachithanantham R", party: "Communist Party of India (Marxist)", constituency: "Dindigul", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Radhakrishna", party: "Indian National Congress", constituency: "Gulbarga (SC)", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri K Radhakrishnan", party: "Communist Party of India (Marxist)", constituency: "Alathur (SC)", state: "Kerala", status: "Sitting", terms: "18" },
  { name: "Shri M K Raghavan", party: "Indian National Congress", constituency: "Kozhikode", state: "Kerala", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri B Y Raghavendra", party: "Bharatiya Janata Party", constituency: "Shimoga", state: "Karnataka", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Kunduru Raghuveer", party: "Indian National Congress", constituency: "Nalgonda", state: "Telangana", status: "Sitting", terms: "18" },
  { name: "Shri Khalilur Rahaman", party: "All India Trinamool Congress", constituency: "Jangipur", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Shri Nityanand Rai", party: "Bharatiya Janata Party", constituency: "Ujiarpur", state: "Bihar", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Rajeev Rai", party: "Samajwadi Party", constituency: "Ghosi", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Ramashankar Vidharthi Rajbhar", party: "Samajwadi Party", constituency: "Salempur", state: "Uttar Pradesh", status: "Sitting", terms: "15,18" },
  { name: "Shri Eatala Rajender", party: "Bharatiya Janata Party", constituency: "Malkajgiri", state: "Telangana", status: "Sitting", terms: "18" },
  { name: "Shri Omprakash Bhupalsinh Alias Pavan Rajenimbalkar", party: "Shiv Sena (Uddhav Balasaheb Thackrey)", constituency: "Osmanabad", state: "Maharashtra", status: "Sitting", terms: "17,18" },
  { name: "Shri Mukesh Rajput", party: "Bharatiya Janata Party", constituency: "Farrukhabad", state: "Uttar Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Mohite Patil Dhairyasheel Rajsinh", party: "Nationalist Congress Party - Sharadchandra Pawar", constituency: "Madha", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Amra Ram", party: "Communist Party of India (Marxist)", constituency: "Sikar", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Vishnu Dayal Ram", party: "Bharatiya Janata Party", constituency: "Palamu (SC)", state: "Jharkhand", status: "Sitting", terms: "16,17,18" },
  { name: "Dr. C M Ramesh", party: "Bharatiya Janata Party", constituency: "Anakapalle", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Ms Kangna Ranaut", party: "Bharatiya Janata Party", constituency: "Mandi", state: "Himachal Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Sukhjinder Singh Randhawa", party: "Indian National Congress", constituency: "Gurdaspur", state: "Punjab", status: "Sitting", terms: "18" },
  { name: "Shri Narayan Tatu Rane", party: "Bharatiya Janata Party", constituency: "Ratnagiri-Sindhudurg", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Dr. Gumma Thanuja Rani", party: "Yuvajana Sramika Rythu Congress Party", constituency: "Araku", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Rajesh Ranjan", party: "Independent", constituency: "Purnia", state: "Bihar", status: "Sitting", terms: "10,11,13,14,16,18" },
  { name: "Shri Daggumalla Prasada Rao", party: "Telugu Desam Party", constituency: "Chittoor (SC)", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Madhavaneni Raghunandan Rao", party: "Bharatiya Janata Party", constituency: "Medak", state: "Telangana", status: "Sitting", terms: "18" },
  { name: "Shri Radheshyam Rathiya", party: "Bharatiya Janata Party", constituency: "Raigarh (ST)", state: "Chhattisgarh", status: "Sitting", terms: "18" },
  { name: "Shri Rakesh Rathor", party: "Indian National Congress", constituency: "Sitapur", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Jashubhai Bhilubhai Rathva", party: "Bharatiya Janata Party", constituency: "Chhota Udaipur (ST)", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Dr. Mallu Ravi", party: "Indian National Congress", constituency: "Nagarkurnool (SC)", state: "Telangana", status: "Sitting", terms: "10,12,18" },
  { name: "Dr. Manna Lal Rawat", party: "Bharatiya Janata Party", constituency: "Udaipur (ST)", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Ashok Kumar Rawat", party: "Bharatiya Janata Party", constituency: "Misrikh", state: "Uttar Pradesh", status: "Sitting", terms: "14,15,17,18" },
  { name: "Shri Trivendra Singh Rawat", party: "Bharatiya Janata Party", constituency: "Hardwar", state: "Uttarakhand", status: "Sitting", terms: "18" },
  { name: "Prof. Sougata Ray", party: "All India Trinamool Congress", constituency: "Dum Dum", state: "West Bengal", status: "Sitting", terms: "6,15,16,17,18" },
  { name: "Shri Bishnu Pada Ray", party: "Bharatiya Janata Party", constituency: "Andaman and Nicobar Islands", state: "Andaman and Nicobar Islands", status: "Sitting", terms: "13,15,16,18" },
  { name: "Smt. Sandhya Ray", party: "Bharatiya Janata Party", constituency: "Bhind (SC)", state: "Madhya Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Chamala Kiran Kumar Reddy", party: "Indian National Congress", constituency: "Bhongir", state: "Telangana", status: "Sitting", terms: "18" },
  { name: "Shri G Kishan Reddy", party: "Bharatiya Janata Party", constituency: "Secunderabad", state: "Telangana", status: "Sitting", terms: "17,18" },
  { name: "Shri Konda Vishweshwar Reddy", party: "Bharatiya Janata Party", constituency: "Chevella", state: "Telangana", status: "Sitting", terms: "16,18" },
  { name: "Shri Magunta Sreenivasulu Reddy", party: "Telugu Desam Party", constituency: "Ongole", state: "Andhra Pradesh", status: "Sitting", terms: "12,14,15,17,18" },
  { name: "Shri P V Midhun Reddy", party: "Yuvajana Sramika Rythu Congress Party", constituency: "Rajampet", state: "Andhra Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Ramasahayam Raghuram Reddy", party: "Indian National Congress", constituency: "Khammam", state: "Telangana", status: "Sitting", terms: "18" },
  { name: "Shri Y S Avinash Reddy", party: "Yuvajana Sramika Rythu Congress Party", constituency: "Kadapa", state: "Andhra Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Zia Ur Rehman", party: "Samajwadi Party", constituency: "Sambhal", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Kiren Rijiju", party: "Bharatiya Janata Party", constituency: "Arunachal West", state: "Arunachal Pradesh", status: "Sitting", terms: "14,16,17,18" },
  { name: "Shri Rajkumar Roat", party: "Bharat Adivasi Party", constituency: "Banswara (ST)", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Dr. Jayanta Kumar Roy", party: "Bharatiya Janata Party", constituency: "Jalpaiguri (SC)", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Smt. Mala Roy", party: "All India Trinamool Congress", constituency: "Kolkata Dakshin", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Smt. Satabdi Roy", party: "All India Trinamool Congress", constituency: "Birbhum", state: "West Bengal", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Rajiv Pratap Rudy", party: "Bharatiya Janata Party", constituency: "Saran", state: "Bihar", status: "Sitting", terms: "11,13,16,17,18" },
  { name: "Shri Parshottambhai Rupala", party: "Bharatiya Janata Party", constituency: "Rajkot", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Shri Matheswaran V S", party: "Dravida Munnetra Kazhagam", constituency: "Namakkal", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Murasoli S", party: "Dravida Munnetra Kazhagam", constituency: "Thanjavur", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Arun Kumar Sagar", party: "Bharatiya Janata Party", constituency: "Shahjahanpur", state: "Uttar Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Bunty Vivek Sahu", party: "Bharatiya Janata Party", constituency: "Chhindwara", state: "Madhya Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Tokhan Sahu", party: "Bharatiya Janata Party", constituency: "Bilaspur", state: "Chhattisgarh", status: "Sitting", terms: "18" },
  { name: "Shri Dilip Saikia", party: "Bharatiya Janata Party", constituency: "Darrang Udalguri", state: "Assam", status: "Sitting", terms: "17,18" },
  { name: "Dr. Swami Sachidanand Hari Sakshi", party: "Bharatiya Janata Party", constituency: "Unnao", state: "Uttar Pradesh", status: "Sitting", terms: "10,11,12,16,17,18" },
  { name: "Dr. M P Abdussamad Samadani", party: "Indian Union Muslim League", constituency: "Ponnani", state: "Kerala", status: "Sitting", terms: "17,18" },
  { name: "Shri Saleng A Sangma", party: "Indian National Congress", constituency: "Tura (ST)", state: "Meghalaya", status: "Sitting", terms: "18" },
  { name: "Dr. Rajkumar Sangwan", party: "Rashtriya Lok Dal", constituency: "Baghpat", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Pratap Chandra Sarangi", party: "Bharatiya Janata Party", constituency: "Balasore", state: "Odisha", status: "Sitting", terms: "17,18" },
  { name: "Smt. Aparajita Sarangi", party: "Bharatiya Janata Party", constituency: "Bhubaneswar", state: "Odisha", status: "Sitting", terms: "17,18" },
  { name: "Dr. Sharmila Sarkar", party: "All India Trinamool Congress", constituency: "Bardhaman Purba (SC)", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Jagannath Sarkar", party: "Bharatiya Janata Party", constituency: "Ranaghat (SC)", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Adv Priya Saroj", party: "Samajwadi Party", constituency: "Machhlishahr", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Daroga Prasad Saroj", party: "Samajwadi Party", constituency: "Lalganj", state: "Uttar Pradesh", status: "Sitting", terms: "12,14,18" },
  { name: "Shri Pushpendra Saroj", party: "Samajwadi Party", constituency: "Kaushambi (SC)", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Dr. Hemant Vishnu Savara", party: "Bharatiya Janata Party", constituency: "Palghar (ST)", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Arvind Ganpat Sawant", party: "Shiv Sena (Uddhav Balasaheb Thackrey)", constituency: "Mumbai South", state: "Maharashtra", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Muhammed Hamdullah Sayeed", party: "Indian National Congress", constituency: "Lakshadweep (ST)", state: "Lakshadweep", status: "Sitting", terms: "15,18" },
  { name: "Shri Jyotiraditya M Scindia", party: "Bharatiya Janata Party", constituency: "Guna", state: "Madhya Pradesh", status: "Sitting", terms: "13,14,15,16,18" },
  { name: "Smt. Kamaljeet Sehrawat", party: "Bharatiya Janata Party", constituency: "West Delhi", state: "NCT of Delhi", status: "Sitting", terms: "18" },
  { name: "Shri Selvaganapathi T.M.", party: "Dravida Munnetra Kazhagam", constituency: "Salem", state: "Tamil Nadu", status: "Sitting", terms: "13,18" },
  { name: "Shri Sasikanth Senthil", party: "Indian National Congress", constituency: "Tiruvallur (SC)", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Sanjay Seth", party: "Bharatiya Janata Party", constituency: "Ranchi", state: "Jharkhand", status: "Sitting", terms: "17,18" },
  { name: "Shri Avimanyu Sethi", party: "Bharatiya Janata Party", constituency: "Bhadrak (SC)", state: "Odisha", status: "Sitting", terms: "18" },
  { name: "Dr. Byreddy Shabari", party: "Telugu Desam Party", constituency: "Nandyal", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Amit Shah", party: "Bharatiya Janata Party", constituency: "Gandhinagar", state: "Gujarat", status: "Sitting", terms: "17,18" },
  { name: "Smt. Mala Rajya Laxmi Shah", party: "Bharatiya Janata Party", constituency: "Tehri Garhwal", state: "Uttarakhand", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Devesh Shakya", party: "Samajwadi Party", constituency: "Etah", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Dr. Mahesh Sharma", party: "Bharatiya Janata Party", constituency: "Gautam Buddha Nagar", state: "Uttar Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Alok Sharma", party: "Bharatiya Janata Party", constituency: "Bhopal", state: "Madhya Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Anurag Sharma", party: "Bharatiya Janata Party", constituency: "Jhansi", state: "Uttar Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Vishnu Datt Sharma", party: "Bharatiya Janata Party", constituency: "Khajuraho", state: "Madhya Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Smt. Manju Sharma", party: "Bharatiya Janata Party", constituency: "Jaipur", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Abdul Rashid Sheikh", party: "Independent", constituency: "Baramulla", state: "Jammu and Kashmir", status: "Sitting", terms: "18" },
  { name: "Adv. Chandra Shekhar", party: "Azad Samaj Party (Kanshi Ram)", constituency: "Nagina (SC)", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Gajendra Singh Shekhawat", party: "Bharatiya Janata Party", constituency: "Jodhpur", state: "Rajasthan", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Suresh Kumar Shetkar", party: "Indian National Congress", constituency: "Zahirabad", state: "Telangana", status: "Sitting", terms: "15,18" },
  { name: "Shri Jagadish Shettar", party: "Bharatiya Janata Party", constituency: "Belgaum", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Chandubhai Chhaganbhai Shihora", party: "Bharatiya Janata Party", constituency: "Surendranagar", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Dr. Shrikant Eknath Shinde", party: "Shiv Sena", constituency: "Kalyan", state: "Maharashtra", status: "Sitting", terms: "16,17,18" },
  { name: "Ms. Praniti Sushilkumar Shinde", party: "Indian National Congress", constituency: "Solapur (SC)", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Mohibbullah", party: "Samajwadi Party", constituency: "Rampur", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Janardan Singh Sigriwal", party: "Bharatiya Janata Party", constituency: "Maharajganj", state: "Bihar", status: "Sitting", terms: "16,17,18" },
  { name: "Dr. Amar Singh", party: "Indian National Congress", constituency: "Fatehgarh Sahib (SC)", state: "Punjab", status: "Sitting", terms: "17,18" },
  { name: "Dr. Bhola Singh", party: "Bharatiya Janata Party", constituency: "Bulandshahr (SC)", state: "Uttar Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Dr. Jitendra Singh", party: "Bharatiya Janata Party", constituency: "Udhampur", state: "Jammu and Kashmir", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Amritpal Singh", party: "Independent", constituency: "Khadoor Sahib", state: "Punjab", status: "Sitting", terms: "18" },
  { name: "Shri Devendra Singh Alias Bhole Singh", party: "Bharatiya Janata Party", constituency: "Akbarpur", state: "Uttar Pradesh", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Dharambir Singh", party: "Bharatiya Janata Party", constituency: "Bhiwani-Mahendragarh", state: "Haryana", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Dushyant Singh", party: "Bharatiya Janata Party", constituency: "Jhalawar-Baran", state: "Rajasthan", status: "Sitting", terms: "14,15,16,17,18" },
  { name: "Shri Ganesh Singh", party: "Bharatiya Janata Party", constituency: "Satna", state: "Madhya Pradesh", status: "Sitting", terms: "14,15,16,17,18" },
  { name: "Shri Giriraj Singh", party: "Bharatiya Janata Party", constituency: "Begusarai", state: "Bihar", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Kali Charan Singh", party: "Bharatiya Janata Party", constituency: "Chatra", state: "Jharkhand", status: "Sitting", terms: "18" },
  { name: "Shri Karan Bhushan Singh", party: "Bharatiya Janata Party", constituency: "Kaiserganj", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Kirti Vardhan Singh", party: "Bharatiya Janata Party", constituency: "Gonda", state: "Uttar Pradesh", status: "Sitting", terms: "12,14,16,17,18" },
  { name: "Shri Pradeep Kumar Singh", party: "Bharatiya Janata Party", constituency: "Araria", state: "Bihar", status: "Sitting", terms: "15,17,18" },
  { name: "Shri Radha Mohan Singh", party: "Bharatiya Janata Party", constituency: "Purvi Champaran", state: "Bihar", status: "Sitting", terms: "9,11,13,15,16,17,18" },
  { name: "Shri Raja Ram Singh", party: "Communist Party of India (Marxist-Leninist) Liberation", constituency: "Karakat", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Shri Rajiv Ranjan Singh", party: "Janata Dal (United)", constituency: "Munger", state: "Bihar", status: "Sitting", terms: "14,15,17,18" },
  { name: "Shri Rajnath Singh", party: "Bharatiya Janata Party", constituency: "Lucknow", state: "Uttar Pradesh", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Rao Inderjit Singh", party: "Bharatiya Janata Party", constituency: "Gurgaon", state: "Haryana", status: "Sitting", terms: "12,14,15,16,17,18" },
  { name: "Shri Rao Rajendra Singh", party: "Bharatiya Janata Party", constituency: "Jaipur Rural", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Sudhakar Singh", party: "Rashtriya Janata Dal", constituency: "Buxar", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Shri Ujjwal Raman Singh", party: "Indian National Congress", constituency: "Allahabad", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Virendra Singh", party: "Samajwadi Party", constituency: "Chandauli", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Smt. Himadri Singh", party: "Bharatiya Janata Party", constituency: "Shahdol (ST)", state: "Madhya Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Abhay Kumar Sinha", party: "Rashtriya Janata Dal", constituency: "Aurangabad", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Shri Shatrughan Prasad Sinha", party: "All India Trinamool Congress", constituency: "Asansol", state: "West Bengal", status: "Sitting", terms: "15,16,17,18" },
  { name: "Shri Kesineni Sivanath", party: "Telugu Desam Party", constituency: "Vijayawada", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Smt. Shambhavi", party: "Lok Jan Shakti Party (Ram Vilas)", constituency: "Samastipur (SC)", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Shri Mahendra Singh Solanky", party: "Bharatiya Janata Party", constituency: "Dewas (SC)", state: "Madhya Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri V Somanna", party: "Bharatiya Janata Party", constituency: "Tumkur", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Sarbananda Sonowal", party: "Bharatiya Janata Party", constituency: "Dibrugarh", state: "Assam", status: "Sitting", terms: "14,16,18" },
  { name: "Shri Bajrang Manohar Sonwane", party: "Nationalist Congress Party - Sharadchandra Pawar", constituency: "Beed", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Nalin Soren", party: "Jharkhand Mukti Morcha", constituency: "Dumka (ST)", state: "Jharkhand", status: "Sitting", terms: "18" },
  { name: "Shri Adhikari Soumendu", party: "Bharatiya Janata Party", constituency: "Kanthi", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri V K Sreekandan", party: "Indian National Congress", constituency: "Palakkad", state: "Kerala", status: "Sitting", terms: "17,18" },
  { name: "Dr. Rani Srikumar", party: "Dravida Munnetra Kazhagam", constituency: "Tenkasi (SC)", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Tangella Uday Srinivas", party: "Janasena Party", constituency: "Kakinada", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Dr. Indra Hang Subba", party: "Sikkim Krantikari Morcha", constituency: "Sikkim", state: "Sikkim", status: "Sitting", terms: "17,18" },
  { name: "Smt. Anita Subhadarshini", party: "Bharatiya Janata Party", constituency: "Aska", state: "Odisha", status: "Sitting", terms: "18" },
  { name: "Dr. K Sudhakar", party: "Bharatiya Janata Party", constituency: "Chikkballapur", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri K Sudhakaran", party: "Indian National Congress", constituency: "Kannur", state: "Kerala", status: "Sitting", terms: "15,17,18" },
  { name: "Shri Parimal Suklabaidya", party: "Bharatiya Janata Party", constituency: "Silchar (SC)", state: "Assam", status: "Sitting", terms: "18" },
  { name: "Smt. Supriya Sule", party: "Nationalist Congress Party - Sharadchandra Pawar", constituency: "Baramati", state: "Maharashtra", status: "Sitting", terms: "15,16,17,18" },
  { name: "Dr. Alok Kumar Suman", party: "Janata Dal (United)", constituency: "Gopalganj (SC)", state: "Bihar", status: "Sitting", terms: "17,18" },
  { name: "Shri Kodikunnil Suresh", party: "Indian National Congress", constituency: "Mavelikkara (SC)", state: "Kerala", status: "Sitting", terms: "9,10,11,13,15,16,17,18" },
  { name: "Smt. Dhanorkar Pratibha Suresh", party: "Indian National Congress", constituency: "Chandrapur", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Tejasvi Surya", party: "Bharatiya Janata Party", constituency: "Bangalore South", state: "Karnataka", status: "Sitting", terms: "17,18" },
  { name: "Shri Bharatbhai Manubhai Sutariya", party: "Bharatiya Janata Party", constituency: "Amreli", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Ms. Bansuri Swaraj", party: "Bharatiya Janata Party", constituency: "New Delhi", state: "NCT of Delhi", status: "Sitting", terms: "18" },
  { name: "Thiru Thanga Tamilselvan", party: "Dravida Munnetra Kazhagam", constituency: "Theni", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Ajay Tamta", party: "Bharatiya Janata Party", constituency: "Almora (SC)", state: "Uttarakhand", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Kanwar Singh Tanwar", party: "Bharatiya Janata Party", constituency: "Amroha", state: "Uttar Pradesh", status: "Sitting", terms: "16,18" },
  { name: "Shri Bibhu Prasad Tarai", party: "Bharatiya Janata Party", constituency: "Jagatsinghpur (SC)", state: "Odisha", status: "Sitting", terms: "15,18" },
  { name: "Shri Kamakhya Prasad Tasa", party: "Bharatiya Janata Party", constituency: "Kaziranga", state: "Assam", status: "Sitting", terms: "16,18" },
  { name: "Shri Krishna Prasad Tenneti", party: "Telugu Desam Party", constituency: "Bapatla", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Manish Tewari", party: "Indian National Congress", constituency: "Chandigarh", state: "Chandigarh", status: "Sitting", terms: "15,17,18" },
  { name: "Smt. Geniben Nagaji Thakor", party: "Indian National Congress", constituency: "Banaskantha", state: "Gujarat", status: "Sitting", terms: "18" },
  { name: "Shri Anurag Singh Thakur", party: "Bharatiya Janata Party", constituency: "Hamirpur", state: "Himachal Pradesh", status: "Sitting", terms: "14,15,16,17,18" },
  { name: "Shri Devesh Chandra Thakur", party: "Janata Dal (United)", constituency: "Sitamarhi", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Shri Gopal Jee Thakur", party: "Bharatiya Janata Party", constituency: "Darbhanga", state: "Bihar", status: "Sitting", terms: "17,18" },
  { name: "Shri Shantanu Thakur", party: "Bharatiya Janata Party", constituency: "Bangaon (SC)", state: "West Bengal", status: "Sitting", terms: "17,18" },
  { name: "Shri Vivek Thakur", party: "Bharatiya Janata Party", constituency: "Nawada", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Smt. Savitri Thakur", party: "Bharatiya Janata Party", constituency: "Dhar (ST)", state: "Madhya Pradesh", status: "Sitting", terms: "16,18" },
  { name: "Dr. T Sumathy Alias Thamizhachi Thangapandian", party: "Dravida Munnetra Kazhagam", constituency: "Chennai South", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Dr. Shashi Tharoor", party: "Indian National Congress", constituency: "Thiruvananthapuram", state: "Kerala", status: "Sitting", terms: "15,16,17,18" },
  { name: "Dr. Thirumaavalavan Tholkappiyan", party: "Viduthalai Chiruthaigal Katchi", constituency: "Chidambaram (SC)", state: "Tamil Nadu", status: "Sitting", terms: "15,17,18" },
  { name: "Shri Manoj Tigga", party: "Bharatiya Janata Party", constituency: "Alipurduars (ST)", state: "West Bengal", status: "Sitting", terms: "18" },
  { name: "Shri Amarsing Tisso", party: "Bharatiya Janata Party", constituency: "Diphu (ST)", state: "Assam", status: "Sitting", terms: "18" },
  { name: "Shri Manoj Tiwari", party: "Bharatiya Janata Party", constituency: "North East Delhi", state: "NCT of Delhi", status: "Sitting", terms: "16,17,18" },
  { name: "Shri Shivmangal Singh Tomar", party: "Bharatiya Janata Party", constituency: "Morena", state: "Madhya Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri E Tukaram", party: "Indian National Congress", constituency: "Bellary (ST)", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Shri Durgadas D D Uikey", party: "Bharatiya Janata Party", constituency: "Betul (ST)", state: "Madhya Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Shri Saptagiri Sankar Ulaka", party: "Indian National Congress", constituency: "Koraput (ST)", state: "Odisha", status: "Sitting", terms: "17,18" },
  { name: "Shri Rajmohan Unnithan", party: "Indian National Congress", constituency: "Kasaragod", state: "Kerala", status: "Sitting", terms: "17,18" },
  { name: "Com. Selvaraj V", party: "Communist Party of India", constituency: "Nagapattinam (SC)", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Smt. Priyanka Gandhi Vadra", party: "Indian National Congress", constituency: "Wayanad", state: "Kerala", status: "Sitting", terms: "18" },
  { name: "Shri Durai Vaiko", party: "Marumalarchi Dravida Munnetra Kazhagam", constituency: "Tiruchirappalli", state: "Tamil Nadu", status: "Sitting", terms: "18" },
  { name: "Shri Ve Vaithilingam", party: "Indian National Congress", constituency: "Puducherry", state: "Puducherry", status: "Sitting", terms: "17,18" },
  { name: "Shri Balashowry Vallabhaneni", party: "Janasena Party", constituency: "Machilipatnam", state: "Andhra Pradesh", status: "Sitting", terms: "14,17,18" },
  { name: "Shri Anoop Pradhan Valmiki", party: "Bharatiya Janata Party", constituency: "Hathras", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Richard Vanlalhmangaiha", party: "Zoram Peoples Movement", constituency: "Mizoram (ST)", state: "Mizoram", status: "Sitting", terms: "18" },
  { name: "Shri Vijayakumar Alias Vijay Vasanth", party: "Indian National Congress", constituency: "Kanniyakumari", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Shri Chavan Ravindra Vasantrao", party: "Indian National Congress", constituency: "Nanded", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Mansukhbhai Dhanjibhai Vasava", party: "Bharatiya Janata Party", constituency: "Bharuch", state: "Gujarat", status: "Sitting", terms: "12,13,14,15,16,17,18" },
  { name: "Shri Parbhubhai Nagarbhai Vasava", party: "Bharatiya Janata Party", constituency: "Bardoli (ST)", state: "Gujarat", status: "Sitting", terms: "16,17,18" },
  { name: "Dr. Kalanidhi Veeraswamy", party: "Dravida Munnetra Kazhagam", constituency: "Chennai North", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Shri Prabhakar Reddy Vemireddy", party: "Telugu Desam Party", constituency: "Nellore", state: "Andhra Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri S Venkatesan", party: "Communist Party of India (Marxist)", constituency: "Madurai", state: "Tamil Nadu", status: "Sitting", terms: "17,18" },
  { name: "Shri K C Venugopal", party: "Indian National Congress", constituency: "Alappuzha", state: "Kerala", status: "Sitting", terms: "15,16,18" },
  { name: "Shri Lalji Verma", party: "Samajwadi Party", constituency: "Ambedkar Nagar", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Rajesh Verma", party: "Lok Jan Shakti Party (Ram Vilas)", constituency: "Khagaria", state: "Bihar", status: "Sitting", terms: "18" },
  { name: "Shri Ram Shiromani Verma", party: "Samajwadi Party", constituency: "Shrawasti", state: "Uttar Pradesh", status: "Sitting", terms: "17,18" },
  { name: "Mrs Ruchi Vira", party: "Samajwadi Party", constituency: "Moradabad", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Yaduveer Wadiyar", party: "Bharatiya Janata Party", constituency: "Mysore", state: "Karnataka", status: "Sitting", terms: "18" },
  { name: "Smt. Smita Uday Wagh", party: "Bharatiya Janata Party", constituency: "Jalgaon", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Ravindra Dattaram Waikar", party: "Shiv Sena", constituency: "Mumbai North West", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Rajabhau Parag Prakash Waje", party: "Shiv Sena (Uddhav Balasaheb Thackrey)", constituency: "Nashik", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Shri Bhausaheb Rajaram Wakchaure", party: "Shiv Sena (Uddhav Balasaheb Thackrey)", constituency: "Shirdi (SC)", state: "Maharashtra", status: "Sitting", terms: "15,18" },
  { name: "Shri Balwant Baswant Wankhade", party: "Indian National Congress", constituency: "Amravati (SC)", state: "Maharashtra", status: "Sitting", terms: "18" },
  { name: "Dr. Lata Wankhede", party: "Bharatiya Janata Party", constituency: "Sagar", state: "Madhya Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Amrinder Singh Raja Warring", party: "Indian National Congress", constituency: "Ludhiana", state: "Punjab", status: "Sitting", terms: "18" },
  { name: "Shri Aditya Yadav", party: "Samajwadi Party", constituency: "Badaun", state: "Uttar Pradesh", status: "Sitting", terms: "18" },
  { name: "Shri Akhilesh Yadav", party: "Samajwadi Party", constituency: "Kannauj", state: "Uttar Pradesh", status: "Sitting", terms: "13,14,15,17,18" },
  { name: "Shri Akshay Yadav", party: "Samajwadi Party", constituency: "Firozabad", state: "Uttar Pradesh", status: "Sitting", terms: "16,18" },
  { name: "Shri Ashok Kumar Yadav", party: "Bharatiya Janata Party", constituency: "Madhubani", state: "Bihar", status: "Sitting", terms: "17,18" },
  { name: "Shri Bhupender Yadav", party: "Bharatiya Janata Party", constituency: "Alwar", state: "Rajasthan", status: "Sitting", terms: "18" },
  { name: "Shri Dharmendra Yadav", party: "Samajwadi Party", constituency: "Azamgarh", state: "Uttar Pradesh", status: "Sitting", terms: "14,15,16,18" },
  { name: "Shri Dinesh Chandra Yadav", party: "Janata Dal (United)", constituency: "Madhepura", state: "Bihar", status: "Sitting", terms: "11,13,15,17,18" },
  { name: "Shri Giridhari Yadav", party: "Janata Dal (United)", constituency: "Banka", state: "Bihar", status: "Sitting", terms: "11,14,17,18" },
  { name: "Shri Surendra Prasad Yadav", party: "Rashtriya Janata Dal", constituency: "Jahanabad", state: "Bihar", status: "Sitting", terms: "12,18" },
  { name: "Smt. Dimple Yadav", party: "Samajwadi Party", constituency: "Mainpuri", state: "Uttar Pradesh", status: "Sitting", terms: "15,16,17,18" },
  { name: "Mr Pathan Yusuf", party: "All India Trinamool Congress", constituency: "Baharampur", state: "West Bengal", status: "Sitting", terms: "18" }
];
